### ISSUE TITLE
UpdateAppleSUSCatalog-related failures

### ISSUE THREAD

**Issue by arubdesu** [google/simian#66]
This error is cropping up on a good number of machines running a relatively recent version:
```py
WARNING:root:Root CA Cert Chain was EMPTY!
ERROR:root:Failed to harvest Puppet SSL cert facter specified.
WARNING:root:Root CA Cert Chain was EMPTY!
Traceback (most recent call last):
  File "/usr/local/munki/simian_client.py", line 87, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/munki/simian_client.py", line 73, in main
    preflight.RunPreflight(runtype, server_url=server_url)
  File "/usr/local/munki/simian/lib/python2.7/site-packages/simian-2.5-py2.7.egg/simian/mac/client/preflight.py", line 429, in RunPreflight
    flight_common.UpdateAppleSUSCatalog(client)
  File "/usr/local/munki/simian/lib/python2.7/site-packages/simian-2.5-py2.7.egg/simian/mac/client/flight_common.py", line 560, in UpdateAppleSUSCatalog
    raise base_client.HTTPError
simian.client.client.HTTPError
```
Any hints as to why this http response is only failing for a handful of clients? I'm trying to correlate OS versions or other discrepancies, since it seems to be in a routine that is supposed to fetch the applicable SUS catalog.

**Comment by maximermilov** [comment]
> File "/usr/local/munki/simian/lib/python2.7/site-packages/simian-2.5-py2.7.egg/simian/mac/client/flight_common.py", line 560, in UpdateAppleSUSCatalog
>    raise base_client.HTTPError
> simian.client.client.HTTPError

Seems like regular network error.

> Any hints as to why this http response is only failing for a handful of clients?

is it persistent?

if it's not an network error, logs from server side for failed request
can be helpful.


_____
Maxim
