### ISSUE TITLE
Support oAuth2 authorization

### ISSUE THREAD

**Issue by Luzifer** [google/simian#7]
When using MFA on Google Apps the `appcfg.py` command needs to get called with `--oauth2` parameter.

### Without `--oauth2`

```
luzifer@knut-workstation01 ~/g/simian (master ••) [2]> make release
src/simian/util/create_gae_bundle.sh /Users/luzifer/git/simian
sed -i "" "s/^application:.*/application: `PYTHONPATH=. python src/simian/util/appid_generator.py`/" gae_bundle/app.yaml
src/simian/util/link_module.sh PyYAML
src/simian/util/link_module.sh pytz
src/simian/util/link_module.sh tlslite
src/simian/util/link_module.sh pyasn1
src/simian/util/link_module.sh icalendar
VE/bin/python src/simian/util/compile_js.py gae_bundle/simian/mac/admin/js/simian.js
appcfg.py --version=bcfc590c1ec7 update gae_bundle/
02:09 PM Application: mysimian; version: bcfc590c1ec7 (was: 1)
02:09 PM Host: appengine.google.com
Traceback (most recent call last):
  File "/usr/local/bin/appcfg.py", line 127, in <module>
    run_file(__file__, globals())
  File "/usr/local/bin/appcfg.py", line 123, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appcfg.py", line 5397, in <module>
[...]
```

### With `--oauth2`

```
luzifer@knut-workstation01 ~/g/simian (master ••)> make release
src/simian/util/create_gae_bundle.sh /Users/luzifer/git/simian
sed -i "" "s/^application:.*/application: `PYTHONPATH=. python src/simian/util/appid_generator.py`/" gae_bundle/app.yaml
src/simian/util/link_module.sh PyYAML
src/simian/util/link_module.sh pytz
src/simian/util/link_module.sh tlslite
src/simian/util/link_module.sh pyasn1
src/simian/util/link_module.sh icalendar
VE/bin/python src/simian/util/compile_js.py gae_bundle/simian/mac/admin/js/simian.js
appcfg.py --version=bcfc590c1ec7 --oauth2 update gae_bundle/
02:15 PM Application: mysimian; version: bcfc590c1ec7 (was: 1)
02:15 PM Host: appengine.google.com
02:15 PM
Starting update of app: mysimian, version: bcfc590c1ec7
[...]
```

**Comment by Luzifer** [comment]
My patch to work around this issue temporarily:

```diff
diff --git a/Makefile b/Makefile
index 8828d9f..5603adc 100644
--- a/Makefile
+++ b/Makefile
@@ -266,5 +266,5 @@ pkg: ${SIMIAN}-and-${MUNKI}.pkg
 dmg: ${SIMIAN}-and-${MUNKI}.dmg

 release: server_config
-       appcfg.py --version=${BUILD_VERSION} update gae_bundle/
-       appcfg.py --version=${BUILD_VERSION} set_default_version gae_bundle/
+       appcfg.py --version=${BUILD_VERSION} --oauth2 update gae_bundle/
+       appcfg.py --version=${BUILD_VERSION} --oauth2 set_default_version gae_bundle/
```

**Comment by juofmgoblue** [comment]
Added support here: b19f15bc2996c9878802d26ca02722176b3cb029

Thanks for the report!
